.TH BeamerPresenter 1 "2022-01-02" "0.2.1"
.SH NAME
BeamerPresenter \- modular multi-screen PDF presenter
.
.SH SYNOPSIS
.
.SY beamerpresenter
.RB [ \-c
.IR config-file ]
.RB [ \-g
.IR ui-file ]
.RB [ \-\-log ]
.RB [ \-t
.IR time ]
.RB [ \-\-renderer
.IR name ]
.I presentation
.RI [ notes
\&.\|.\|.\&]
.SY beamerpresenter
.RB [ \-h | \-\-help | \-\-help-all | \-v | \-\-version ]
.
.
.SH DESCRIPTION
.
.B BeamerPresenter
is a Qt-based presentation viewer designed for showing extra information on the speaker's screen.
The modular user interface is completely customizable and may include, among others, previews of upcoming slides, a different presentation file with additional information, text notes, a timer, and thumbnail slides.
.PP
The interpretation of multiple positional arguments depends on the user interface configuration (beamerpresenter-ui (5)). Readable file types are PDF files and (optionally gzip compressed) xml files in the format defined by Xournal++ (.xopp).
.
.
.SH OPTIONS
.
.TP
.B \-h \-\-help
Displays help.
.
.TP
.B \-\-help-all
Displays help including Qt-specific options.
.
.TP
.B \-v \-\-version
Displays version information.
.
.TP
.BI "\-\-renderer " option
Define renderer and PDF engine. Depending on you installation, this may be MuPDF, poppler, MuPDF-external or poppler-external. "external" indicates that instead of using the given PDF engine, the rendering should be delegated to an external program. The command for calling this program must be defined in the configuration, see beamerpresenter.conf(5).
.
.TP
.B \-\-log
Print times of slide changes to standard output. Only has an effect if a page label/number widget is contained in GUI.
.
.TP
.BI "\-\-debug " "flag1,flag2,..."
Show debugging messages. Only available if buit with the option CONFIG+=debug. Valid flags are: rendering, cache, drawing, media, key-input, other-input, settings, transitions, page-change, layout, widets, all, verbose. The "verbose" option does not turn on any logging by itself, but shows additional logging for the other flags set.
.
.TP
.BI "\-t \-\-time " number
Timer preset in minutes (floating point number).
.
.TP
.BI "\-c \-\-config " file
Path to config (settings) file.
.
.TP
.BI "\-g \-\-gui-config " file
Path to user interface configuration file (json-formatted).
.
.
.SH DEFAULT KEY BINDINGS
.
.TP
.B PageUp
.B previous
Go to previous page.
.
.TP
.B PageDown
.B next
Go to next page.
.
.TP
.B space
.B update
Refresh view.
.
.
.SH CONFIGURATION
.
The configuration consists of an ordinary config file (beamerpresenter.conf(5)) based on Qt's settings format, which is integrated in the system settings. This defines, e.g., the cache size and keyboard shortcuts. Additionally the graphical interface is defined in a json-formatted file gui.json (beamerpresenter-ui (5)). This is used to arrange and configure windows and widgets (such as sides, clock, timer, overview, ...).
.
.
.SH FILE FORMAT
.
BeamerPresenter can save drawings along with notes (from notes widget) and other file-specific settings to a gzipped xml file (.bpr). The pdf file is not included in this file.
The file type aims for compatibility with Xournal++ in saving and loading drawings. BeamerPresenter can read Xournal(++) files and Xournal++ can open BeamerPresenter files. If this does not work, please open an issue on https://github.com/stiglers-eponym/BeamerPresenter.
When opening a file, it does not need to be gzipped. However, when saving to a file, it will always be gzipped.
.
.
.SH BUGS
.
Bugs should be reported at the
.UR https://github.com/stiglers-eponym/BeamerPresenter/issues
issue tracker
.UE .
.
.
.
.SH SEE ALSO
.
.BR beamerpresenter.conf (5),
.BR beamerpresenter-ui (5)

There are other programs which show notes along a PDF. Some examples are
.BR pdfpc (1)
.BR pympress "(1) and"
.BR dspdfviewer (1)
