.TH beamerpresenter-ui 5 "2022-04-18" "0.2.2"
.
.SH NAME
beamerpresenter-ui \- user interface of BeamerPresenter
.
.
.SH GENERAL
.
The GUI configuration file is JSON-formatted, containing a list of widgets. These widgets function as root widgets forming own windows. Each widget is a JSON dictionary. There are widgets providing their own content and layout widgets which do not provide own contents, but contain a list of child widgets.
.PP
Example configuration files can be found in /usr/share/doc/beamerpresenter/examples/.
.PP
Arguments shared by all widgets:
.TP
.BI "type" " name"
widget type defined in section WIDGETS
.TP
.BI "keys " "keyboard shortcut"
Key combination to set focus to this widget.
.TP
.BI "title " "text"
title of the widget, visible only if the widget is shown in a tabbed widget.
.TP
.BI "color " "color name / #RRGGBB / #AARRGGBB"
background color, color name known to Qt. Some Qt styles may override colors set in the GUI config.
.PP
Arguments for all top level widgets (widgets that are shown as windows):
.TP
.BI "always show " bool
This window should always be shown on top of other windows if the window manager supports that. Default value is false except if the widget is of type "tool selector".
.
.SH WIDGETS
.
.TP
.B clock
digital clock.
This widget lets you start the timer with a double click on the clock or by tapping on the clock on a touch screen.
.RS
.PP
Arguments:
.TP
.BI "touch input " true/false
Start/stop the timer by touching the clock.
.RE
.
.TP
.B notes
rich text editable notes.
Notes are included when saving drawings to gzipped xml file (.bpr/.xopp).
Alternatively, they can be saved separately in an xml file using the keyboard actions while the notes widget has focus:
save notes with Ctrl+S, save under new file name with Ctrl+Shift+S, open from file with Ctrl+O.
Currently the notes are saved as HTML string, which is escaped when saving in xml format. This format might change in the future!
.RS
.PP
Arguments:
.TP
.B identifier
\[dq]label\[dq] or \[dq]number\[dq]: notes are associated with a page (number) or a group of pages with the same page label.
.TP
.BI "zoom " "integer"
zoom step for the widget (defined by QTextEdit).
.TP
.BI "file " "path"
path to xml-file to read notes from. The notes file contains a root element <speakernotes> with child elements <page-notes> containing the rich text notes. Each page element has an attribute "label" or "number" to identify a page or a group of pages. Which of "label" or "number" is used must be specified by the attribute "identifier" or the root element.

Example file:
.nf
.eo
<?xml version="1.0" encoding="UTF-8"?>
<speakernotes identifier="label">
<page-notes label="1">notes on first page
</page-notes>
<page-notes label="2">notes on second page
</page-notes>
</speakernotes>
.ec
.fi
.RE
.
.TP
.B settings
change settings and get help. Most of this module is not implemented yet.
.
.TP
.B slide
slide of a presentation. This is the main widget shown to the audience and on the speaker's screen.
.RS
.PP
Arguments:
.TP
.BI "file " "path"
pdf file shown in the presentation or alias name. Aliases such as "presentation" or "notes" will be filled with command line arguments or by asking in a file open dialog.
.TP
.BI "shift " "integer"
shift slide number relative to the main presentation slide. E.g. shift=1 creates a preview of the next slide, which can be shown in the speaker's view.
.TP
.BI "page part " "left/right"
side of the page to be shown if the pages are split into a left and a right side showing presentation and notes on the same page.
.TP
.BI "media controls " "= false"
show/hide a slider to navigate inside a video
.TP
.BI "show tools " "= true"
enable/disable pointing tools.
.TP
.BI "media " "= true"
enable/disable multimedia content on this widget.
.B Caution:
If multiple widgets show the same slide, the configuration of one of these widgets is used for the other widgets. Switching off multimedia for one widget may also disable multimedia for other widgets.
.TP
.BI "mute " "= true"
mute or unmute the slide connected to this widget.
By default normal slides are muted and slides marked as "master" are unmuted.
Make sure that exactly one slide widget is unmuted in the GUI configuration (typically the presentation slide widget).
.TP
.BI "transitions " "= true"
enable/disable slide transitions.
.B Caution:
If multiple widgets show the same slide, the configuration of one of these widgets is used for the other widgets. Switching off transitions for one widget may also disable transitions for other widgets.
.TP
.BI "autoplay " "= true"
automatically play videos on this slide.
.B Caution:
If multiple widgets show the same slide, the configuration of one of these widgets is used for the other widgets. Switching off autoplay for one widget may also disable it for other widgets.
.TP
.BI "cache videos " "= true"
cache videos before the slide with the video is reached.
.B Caution:
If multiple widgets show the same slide, the configuration of one of these widgets is used for the other widgets.
.TP
.BI "draw " "= true"
enable/disable drawing on the this widget.
.B Caution:
If multiple widgets show the same slide, the configuration of one of these widgets is used for the other widgets. Disabling drawing for one widget may disable it also for other ones.
.TP
.BI "cache hash " "integer"
integer to identify slide widgets with the same geometry, which should use the same cached slides. Set the same \[dq]cache hash\[dq] for multiple slides to make them use the same cache. Note that this can also cause problems if the geometry of the widgets is not exactly the same.
.TP
.BI "threads " "integer"
number of threads used to pre-render pages in cache. Disable pre-rendering by setting this to zero.
.TP
.BI "overlays " "first/last/none"
show only first/last page of each group of pages with the same page label.
.RE
.
.TP
.B slide label
Show label of current slide and allow navigation by editing the slide label.
.
.TP
.B slide number
Show number of current slide and allow navigation by editing this number.
.
.TP
.B thumbnails
thumbnail overview of all slides.
.PP
.RS
Arguments:
.TP
.BI "overlays " "skip"
Set this option to \[dq]skip\[dq] to show only one preview slide for each group of pages with the same page label.
.TP
.BI "columns " "integer"
number of columns in which the thumbnail slides are arranged.
.RE
.
.TP
.B timer
timer for the presentation.
Both the total time and the passed time are editable text fields. By double-clicking between these two text fields you can store the passed time (left field) as the target time for the currently visible page. These times per page are stored when saving drawings. The times per page are used to indicate the current progress relative to the planned progress by the background color of the passed time text field.
.PP
.RS
Arguments:
.TP
.BI "require confirmation " "bool"
Ask for confirmation before setting the time for a slide.
.TP
.BI "confirmation default " "bool"
When asking for confirmation when setting the time for a slide, this will be the default (accept or cancel). The default value is false.
.TP
.BI colormap " JSON object"
Customize the function mapping the current time relative to the target time of the current slide to a color. This JSON object maps times (as integers, in seconds) to colors (e.g. in #rrggbb format). Positive times indicate that the speaker has this amount of time left. Between the times defined in this map, a linear interpolation is used.

Default configuration:
.nf
.eo
"colormap" : {
    "-300" : "#ff0000",
    "-90"  : "#ffff00",
    "0"    : "#00ff00",
    "90"   : "#00ffff",
    "300"  : "#ffffff"
    }
.ec
.fi
.RE
.
.TP
.B toc
outline / table of contents, shows document outline tree.
.
.TP
.B tool selector
grid layout of push buttons. Contains mandatory argument
.B buttons
which must be an array of arrays of buttons. The array of arrays constitutes a matrix defining the arrangement of the buttons.
Each button can either be a string representing an action, or a string defining a tool property, or a JSON dictionary defining a tool property and a selection of values for this property, or a JSON dictionary representing a tool, or an array of multiple strings representing actions.
.RS
.PP
Valid action strings:
.TP
.B previous
navigate to previous page
.TP
.B next
navigate to next page
.TP
.B first
navigate to first page
.TP
.B last
navigate to last page
.TP
.B update
update view (technically navigates to current page)
.TP
.B next skipping overlay
navigate to next page which has a different page label than current page
.TP
.B previous skipping overlays
navigate to previous page which has a different page label than current page
.TP
.B reload
reload the presentation pdf (if it has been modified).
.TP
.B undo
undo last drawing action on current page
.TP
.BR "undo left" / right
undo last drawing action on left/right part of current page, assuming that the page is split into a left and right half which represent presentation and notes, respectively
.TP
.B redo
redo last drawing action on current page
.TP
.BR "redo left" / right
redo last drawing action on left/right part of current page, assuming that the page is split into a left and right half which represent presentation and notes, respectively
.TP
.B clear
clear all drawings on the current page.
.TP
.BR "clear left" / right
clear all drawings on the left/right part of current page, assuming that the page is split into a left and right half which represent presentation and notes, respectively
.TP
.BR "scroll up" / normal / down
scroll the slide view up / to normal position / down. This allows the presenter to add extra space for drawings.
.TP
.B save
save drawings to file. Doesn't ask for file name if a file name is known.
.TP
.B save as
save drawings to file. Always asks for the file name.
.TP
.B open
load drawings from file.
.TP
.B open unsafe
load drawings from file without clearing existing paths.
.TP
.B copy
copy selected items on currently focussed slide to clipboard.
.TP
.B paste
paste clipboard on currently focussed slide.
.TP
.B cut
copy selected items on currently focussed slide to clipboard and remove them.
.TP
.B to foregroud
move selected items on currently focussed slide to foreground (not implemented yet).
.TP
.B delete
delete selecte items on currently focussed slide.
.TP
.B duplicate
duplicate selection on curretly focussed slide.
.TP
.B select all
select all items on currently focussed slide.
.TP
.B clear selection
clear selection on currently focussed slide.
.TP
.BR start / stop / "toggle timer"
start or stop timer in timer widget.
.TP
.B reset timer
reset the timer (passed time) in timer widget.
.TP
.BR play / pause / "stop media"
start, pause or stop playing multimedia content.
.TP
.BR mute / unmute
mute or unmute all multimedia content. Media on slides views which are muted in the GUI config are not affected.
.TP
.B fullscreen
toggle full screen view for currently active window.
.TP
.B quit
close BeamerPresenter. Ask for confirmation if there are unsaved changes. Note that the detection of unsaved changes is not reliable yet.
.TP
.B quit unsafe
close BeamerPresenter ignoring unsaved changes.
.
.PP
Valid tool properties are:
.TP
.B shape
drop-down menu of shapes.
.TP
.B style
drop-down menu of pen styles.
.TP
.B color
drop-down menu of colors. This must be provided as a JSON object in the form {"select":"color", "list":["red", "green", "blue"]} were the list of colors can be adapted.
.TP
.B width
drop-down menu of draw tool widths. This must be provided as a JSON object in the form {"select":"width", "list":[0.5,1,2,4]} were the list of widths (measured in point=1/72 inch in the PDF) can be adapted.
.
.PP
Options in the dictionary for tools (all lengths are given in points (1/72 inch) in PDF):
.TP
.B tool
mandatory: pen, fixed width pen, highlighter, eraser, pointer, magnifier, torch, text, click select, rectangle select, or none
.TP
.B color
color name known to Qt or #RRGGBB or #AARRGGBB
.TP
.B width
only draw tools (pen, highlighter, fixed width pen): stroke width (positive number).
.TP
.B size
only pointing tools (eraser, pointer, torch, highlighter): radius of tool (positive number).
.TP
.B fill
only draw tools (pen, highlighter, fixed width pen): color to fill the path. Leave empty if paths should not be filled.
.TP
.BR style " = SolidLine"
only draw tools: Pen style for stroking the path. Possible values are "nopen" , "solid", "dash", "dot", "dashdot", and "dashdotdot".
.TP
.BR brush " = SolidPattern"
only draw tools: Filling style of the path, see https://doc.qt.io/qt-6/qt.html#BrushStyle-enum for valid names. Gradients are not allowed.
.TP
.BR shape " = freehand"
only draw tools (pen, highlighter, fixed width pen): Draw this shape instead of a freehand path. Allowed values are "freehand", "rectangle", "ellipse", "line", and "arrow".
.TP
.BR scale " = 2"
only magnifier: magnification factor (number between 0.1 and 5).
.TP
.BR linewidth " = 0"
only eraser: draw a circle of given line width around the eraser (number). The circle is only drawn on the currently active widget.
.TP
.B font
only text tool: anything that Qt can interpret as font name.
.TP
.B font size
only text tool: font size (positive number).
.PP
It is possible to select a different tool for a button while BeamerPresenter is running by clicking the button while pressing the ctrl key. But note that this changes the tool only temporarily and this modification will not be saved.
.RE

.SS Layouts
.
.TP
.B horizontal
horizontally arranged child widgets. The relative size of the widgets is determined by their preferred aspect ratios to ensure maximal usage of the screen by slide widgets.
.
.TP
.B vertical
vertically arranged child widgets, see horizontal.
.
.TP
.B stacked
stacked child widgets, shown in the same place. The currently visible widget can only be selected by keyboard shortcuts defined using the \[dq]keys\[dq] argument of the subwidgets.
.
.TP
.B tabbed
similar to stacked widget, but shows the child widgets as tabs, which can be selected using the cursor.
.PP
.RS
Arguments:
.TP
.BI "orientation " "north/east/south/west"
position of the tab bar.
.RE
.
.SH SEE ALSO
.
.BR beamerpresenter (1)
.BR beamerpresenter.conf (5),
