.TH beamerpresenter.conf 5 "2022-01-02" "0.2.2_beta"
.
.SH NAME
beamerpresenter.conf \- configuration file for BeamerPresenter
.
.SH DESCRIPTION
.
Configuration file for BeamerPresenter. You can manually edit this file or make changes in the settings widget of BeamerPresenter, which will also be written to this file. Command line arguments temporarily overwrite the settings of the config file.
.PP
The configuration is structured into groups. A group is started by a line of the format
.BI [ name ]
.RI "where " name " is the name of the group.
The group ends when another group is started. Entries not belonging to any group are put in the default group
.IR General .
.
.SS [General]
.
.TP
.BR "engine " "= mupdf"
PDF engine, \[dq]mupdf\[dq] or \[dq]poppler\[dq]. This is ignored if only one PDF engine was enabled at compile time.
.
.TP
.BR "gui config " "= /etc/xdg/beamerpresenter/gui.json"
Path to user interface configuration file. The structure of this file is documented in
.BR beamerpresenter-ui (5).
.
.TP
.BR "manual " "= /usr/share/doc/beamerpresenter/README.html"
Path to HTML-formatted manual, which is shown in the settings widget.
.
.TP
.BR "icon path " "= /usr/share/beamerpresenter/icons/"
Path to directory containing icons for this specific. This must contain the trailing slash.
.
.TP
.B "icon theme"
Icon theme used for (generic) action icons. Choose any icon theme installed on your system.
.
.TP
.B "icon theme path"
Path to icon theme. If Qt does not find your icon theme, you can try to set its path with this option.
.
.TP
.BR "cache pages " "= -1"
Maximum number of pages in cache. A negative number is interpreted as infinity.
.
.TP
.BR "memory " "= 1.0486e+08"
Maximally allows memory used to cache slides, floating point number in bytes.
Note that it is not guaranteed that this limit is always strictly obeyed, since the required memory per page is a priory not known.
.
.TP
.BR "frame time " "= 50"
Frame time (integer, in ms) when showing slides in rapid succession as an animation.
.
.TP
.BR gestures " = true"
Enable or disable gesture navigation (if available). In wayland and Xorg 3 fingers swiping on a touch screen trigger a gesture event. Currently not configurable in the GUI.
.
.TP
.BR "log " "= false"
Log slide changes to standard output.
.
.TP
.BR "show animations " "= true"
Automatically switch slides if the PDF defines a duration for the slide. This can be used for very basic (and quite ugly) animations by showing slides in rapid succession.
.
.TP
.BR "debug " "= flag1,flag2,..."
Only if debugging was enabled at compile time: Show debugging messages for the given flags. Usually debugging flags are defined on the command line and not in the global configuration.
.
.
.SS [drawing]
.
.TP
.BR "history length hidden " "= 20"
Number of steps in drawing history (available undo steps) for slides, which are currently not visible.
.
.TP
.BR "history length visible " "= 50"
Number of steps in drawing history (available undo steps) for the currently active slide.
.
.TP
.BR "mode " "= cumulative"
Defines how drawings are associated to pages. Possible options are:
.RS
.TP
.B per page
Drawings are only connected to one page in the PDF file.
.TP
.B per label
Groups of successive pages which share the same page label have the same drawings. For presentations generated with LaTeX beamer this means that different overlays of the same slide show the same drawings. This mode can cause problems when combined with multimedia or slide transitions.
.TP
.B cumulative
Drawings are connected to pages of the PDF file. But within a group of successive pages with the same page label the drawings of the previous page are copied to the next slide if this next slide does not contain any own drawings. This allows one to successively add drawings in slides, where items appear as overlays with the same page label.
.RE
.
.SS [rendering]
.
.TP
.BR "page part threshold " "= 2.5"
Threshold for the aspect ratio of PDF pages above which it is assumed that a PDF file contains slides and notes for the speaker side-by-side on the same PDF page. For slides generated with LaTeX beamer and the option \[dq]show notes on second screen\[dq] this allows one to show notes for the speak on one screen and presentation slides on a second screen. Note that this only has an effect if the configuration of the user interface
.RB ( beamerpresenter-ui (5))
defines, which parts of the page should be shown on which screen.
.
.TP
.BR "renderer " "= mupdf"
mode for rendering pdf pages. Allowed values \[dq]mupdf\[dq] (if enabled at compile time), \[dq]poppler\[dq] (if enable at compile time) and \[dq]external\[dq] (requires configuration of
.BR "rendering command" " and " "rendering arguments" ).
Note that renderer and pdf engine must agree, i.e., it is not possible to use the poppler engine and mupdf for rendering.
.
.TP
.BR "rendering command"
path to external program used to render pages. This only has an effect if
.BR renderer " is set to " external .
.
.TP
.BR "rendering arguments"
comma-separated list of arguments for external program used to render pages. This only has an effect if
.BR renderer " is set to " external .
The following replacements in the arguments are available:
.RS
.TP
.B %file
absolute path to pdf file
.TP
.B %page
page number, start counting from 1
.TP
.B %0page
page number, start counting from 0
.TP
.B %resolution
resolution in dpi
.TP
.BR %width ", " %height
target image size in pixels
.TP
.B %format
\[dq]png\[dq] or \[dq]pnm\[dq]: image format.
.TP
.B %Format.
\[dq]PNG\[dq] or \[dq]PNM\[dq]: image format.
.RE
.
.SS [keys]
All keyboard shortcut definitions are of the form
.PP
.RS
.IR "key code " = " handler" .
.RE
.PP
Here
.I key code
is anything that Qt can interpret as a key code, e.g., \[dq]A\[dq], \[dq]Shift+B\[dq], or \[dq]Ctrl+Alt+Shift+C\[dq].
For
.I handler
the following formats are allowed:
.TP
.I action
string representing an action. The available actions are listed in
.BR beamerpresenter-ui (5).
.
.TP
.I action1, action2, ...
comma-separated list of actions.
.
.TP
.I JSON dictionary
JSON-formatted dictionary using single quotation marks instead of double quotation marks (alternatively, double quotation marks can be escaped using backslash).
Entries in the dictionary are:
.RS
.TP
.B tool
mandatory: pen, fixed width pen, highlighter, eraser, pointer, magnifier, torch, text or none
.TP
.B device
optional, use the tool for the given devices leaving other devices unchanged. Either a single device or a list (JSON array) of device names is allowed. Available device names are: left button (equivalent: mouse), right button, middle button, no button (only mouse cursor moves), touch, tablet pen, tablet (may include table input which is not recognized as pen), tablet eraser, tablet hover (tablet event with zero pressure), tablet all (any tablet input device), all (devices which are commonly used like left mouse button), all+ (devices except right mouse button, middle mouse button, tablet eraser), all++ (really all devices).
.TP
.B color
color name known to Qt or #RRGGBB or #AARRGGBB
.TP
.B width
only draw tools (pen, highlighter, fixed width pen): stroke width (positive number).
.TP
.B size
only pointing tools (pointer, torch, eraser): radius of tool (positive number).
.TP
.B fill
only draw tools (pen, highlighter, fixed width pen): color to fill the path. Leave empty if paths should not be filled.
.TP
.BR scale " = 2"
only magnifier: magnification factor (number between 0.1 and 5).
.TP
.BR linewidth " = 0"
only eraser: draw a circle of given line width around the eraser (number). The circle is only drawn on the currently active widget.
.TP
.B font
only text tool: anything that Qt can interpret as font name.
.TP
.B font size
only text tool: font size (positive number).
.TP
.B linewidth
only eraser: number, width of circle indicating the size of the eraser.
.PP
Example: {'tool':'pen', 'color':'green', 'width':2, 'device':['tablet pen', 'touch']}
.RE
.
.TP
.I JSON array
array of JSON dictionaries as described before. The dictionaries should contain complementing values for
.BR device .
.
.SS [tools]
Define tools which are initially associated with a devices. The syntax is as follows:
.PP
.RS
.IR "device " = " tool"
.RE
.PP
.RI "Here " device " is a device name as listed above and " tool " is a JSON object representing a tool as described above. If " tool " defines a device (or list of devices), this overwrites " device ". It is therefore also possible to use any unique string or number for " device " and specify the device(s) in the " tool " JSON object."
.PP
An example configuration:
.RS
right button = {'tool':'eraser', 'size':10, 'linewidth':0.5}
table eraser = {'tool':'eraser', 'size':15, 'linewidth':0}
.RE
.
.SH FILES
.
.SH
/etc/xdg/beamerpresenter/beamerpresenter.conf
System-wide configuration file. This file is read before reading also the per-user configuration file.
.
.SH
~/.config/beamerpresenter/beamerpresenter.conf
Per-user configuration file. Changes made through the graphical interface will be saved to this file.
.
.SH SEE ALSO
.
.BR beamerpresenter (1),
.BR beamerpresenter-ui (5)
