.TH BeamerPresenter 1 "2023-04-11" "0.2.3"
.SH NAME
BeamerPresenter \- modular multi-screen PDF presenter
.
.SH SYNOPSIS
.
.SY beamerpresenter
.RB [ \-c
.IR config-file ]
.RB [ \-g
.IR ui-file ]
.RB [ \-\-log ]
.RB [ \-\-nocache ]
.RB [ \-t
.IR time ]
.RB [ \-\-renderer
.IR name ]
.I presentation
.RI [ notes
\&.\|.\|.\&]
.SY beamerpresenter
.RB [ \-h | \-\-help | \-\-help-all | \-v | \-\-version ]
.
.
.SH DESCRIPTION
.
.B BeamerPresenter
is a Qt-based presentation viewer designed for showing extra information on the speaker's screen.
The modular user interface is completely customizable and may include, among others, previews of upcoming slides, a different presentation file with additional information, text notes, a timer, and thumbnail slides.
.PP
The interpretation of multiple positional arguments depends on the user interface configuration (beamerpresenter-ui (5)). Readable file types are PDF files and gzip compressed xml files a format mostly compatible with Xournal++ (.xopp).
.
.
.SH OPTIONS
.
.TP
.B \-h \-\-help
Displays help.
.
.TP
.B \-\-help-all
Displays help including Qt-specific options.
.
.TP
.B \-v \-\-version
Displays version information.
.
.TP
.BI "\-\-renderer " option
.RI "Define renderer and PDF engine. Depending on you installation, this may be just a PDF engine (MuPDF, Poppler, or QtPDF), or \[dq]" ENGINE "-external\[dq] where " ENGINE " is a PDF engine. \[dq]external\[dq] indicates that instead of using the given PDF engine, the rendering should be delegated to an external program. The command for calling this program must be defined in the configuration, see beamerpresenter.conf(5).
.
.TP
.B \-\-log
Print times of slide changes to standard output. Only has an effect if a page label/number widget is contained in GUI.
.
.TP
.B \-\-nocache
Disable caching slides. This option may be helpful when using a presentation with slides of different geometry.
.
.TP
.BI "\-\-debug " "flag1,flag2,..."
Show debugging messages. Only available if built with the option CONFIG+=debug. Valid flags are: rendering, cache, drawing, media, key-input, other-input, settings, transitions, page-change, layout, widgets, all, verbose. The "verbose" option does not turn on any logging by itself, but shows additional logging for the other flags set.
.
.TP
.BI "\-t \-\-time " number
Timer preset in minutes (floating point number).
.
.TP
.BI "\-c \-\-config " file
Path to config (settings) file.
.
.TP
.BI "\-g \-\-gui-config " file
Path to user interface configuration file (json-formatted).
.
.
.SH DEFAULT KEY BINDINGS
.
.TP
.BI "PageUp, Left " "= previous"
Go to previous page
.
.TP
.BI "PageDown, Right " "= next"
Go to next page
.
.TP
.BI "space " "= update"
Refresh view
.
.TP
.BI "Home " "= first"
Go to first page
.
.TP
.BI "End " "= last"
Go to last page
.
.TP
.BI "Ctrl + C " "= copy"
Copy the selection to the clipboard
.
.TP
.BI "Ctrl + V " "= paste"
Paste from the clipboard
.
.TP
.BI "Ctrl + X " "= cut"
Remove selection and copy it to the clipboard
.
.TP
.BI "Ctrl + Z " "= undo"
Undo (e.g. when drawing or adding text)
.
.TP
.BI "Ctrl + Y " "= redo"
.
.TP
.BI "Del " "= delete"
Remove selection.
.
.TP
.BI "Ctrl + S " "= save"
Save drawings, notes, and times (see section FILE FORMAT below)
.
.TP
.BI "Ctrl + Shift + S " "= save as"
.
.TP
.BI "Ctrl + O " "= open"
Load drawings etc. from file.
.
.
.SH CONFIGURATION
.
The configuration consists of an ordinary config file (beamerpresenter.conf(5)) based on Qt's settings format, which is integrated in the system settings. This defines, e.g., the cache size and keyboard shortcuts. Most settings in this settings file can be configured in the settings widget of the graphical user interface. See command line option -c or --config.
.PP
Additionally, the graphical interface is defined in a json-formatted file gui.json (beamerpresenter-ui(5)). This is used to arrange and configure windows and widgets (such as sides, clock, timer, overview, ...). This file can only be edited manually. See command line option -g or --gui-config.
.
.
.SH FILE FORMAT
.
BeamerPresenter can save drawings along with notes (from notes widget) and other file-specific settings to a gzipped xml file (.bpr). The PDF file is not included in this file.
The file type aims for compatibility with Xournal++'s .xopp in saving and loading drawings. BeamerPresenter can read .xoj and .xopp files, but will only consider pages with a PDF page as background. Xournal++ can open BeamerPresenter files, but transformations of text boxes will be ignored. BeamerPresenter can only handle a very basic subset of the features provided by Xournal++ and also adds a few features which Xournal++ will ignore.
When opening a file, it does not need to be gzipped. However, when saving to a file it will always be gzipped.
.
.
.SH BUGS
.
If you find bugs, please reported these at the
.UR https://github.com/stiglers-eponym/BeamerPresenter/issues
issue tracker
.UE . Please include the output of "beamerpresenter --version" in the bug report.
.PP
The issue tracker can also be used to request features or to make suggestions, e.g., for default configurations or example configurations.
.
.
.
.SH SEE ALSO
.
.BR beamerpresenter.conf (5),
.BR beamerpresenter-ui (5)

There are other programs which show notes along a PDF. Some examples are
.BR pdfpc (1)
.BR pympress "(1) and"
.BR dspdfviewer (1)
