.TH BeamerPresenter 1 "15 April 2019"
.
.SH NAME
BeamerPresenter \- dual-screen PDF presenter
.
.
.SH SYNOPSIS
.
.SY beamerpresenter
.OP \-a autoplay-delay
.OP \-c cache
.OP \-m min-delay
.OP \-M memory
.OP \-p part
.OP \-t timer
.OP \-u char
.I presentation.pdf
.RI [ notes.pdf ]
.
.SY beamerpresenter
.BR \-h " | " \-\-help
.
.
.SH DESCRIPTION
.
.B BeamerPresenter
is a Qt5-based presentation viewer which shows a presentation and notes for the speaker in two different windows. It is designed primarily for usage with LaTeX-beamer generated presentations and notes. Slides and notes must be PDF documents.
.PP
Along with the notes,
.B BeamerPresenter
shows images of the current and next slide and a timer.
.
.
.SH OPTIONS
.
.TP
.B \-h \-\-help
Displays this help.
.
.TP
.BI "\-a \-\-autoplay " delay
true, false or number: Start video and audio content when entering a slide. A number is interpreted as a delay in seconds, after which multimedia content is started.
.
.TP
.BI "\-A \-\-autoplay-emb " delay
true, false or number: Start embedded applications when entering a slide. A number is interpreted as a delay in seconds, after which embedded applications are started.
.
.TP
.BI "\-b \-\-blinds " integer
Set number of blinds in blinds slide transition.
.
.TP
.BI "\-c \-\-cache " integer
Set the maximum number of slides, which are rendered to images and stored in a compressed cache. A negative number is treated as infinity.
.
.TP
.BI "\-e \-\-embed " files
Mark these files for embedding if an execution link points to them. Multiple files should be separated only by a comma (not space!).
.
.TP
.BI "\-f \-\-frame-time " ms
Set the time per frame in slide transitions in ms.
.
.TP
.BI "\-j \-\-json " file
Select a local configuration file. The file must be in JSON format and can contain the same configuration as the global configuration file. Additionally, it can contain a map of slides to times, at which you want to finish the slide. These times are used to adjust the color of the timer.
.
.TP
.BI "\-l \-\-toc-depth " integer
.RB "Number of levels in the table of contents, which will be shown on the control screen with shortcut " t ". Possible values range from 1 and 4. An additional level will be shown as a popup menu if necessary."
.
.TP
.BI "\-m \-\-min-delay " delay
Set minimum time per frame in milliseconds. This is useful when using \\animation in LaTeX beamer.
.
.TP
.BI "\-M \-\-memory " integer
Set the maximum cache size in MiB. A negative number is treated as infinity. The real memory usage can be slightly larger than this limit, because slides are rendered to cache without any knowledge about their size in memory beforehand.
.
.TP
.BI "\-o \-\-columns " integer
Set the number of columns of slides, which will be shown in the overview mode on the control screen.
.
.TP
.BI "\-p \-\-page-part " side
Set half of the page to be the presentation, the other half to be the notes. Values are "l" or "r" for presentation on the left or right half of the page, respectively. If the presentation was created with "\\setbeameroption{show notes on second screen=right}", you should use
.B \-\-page-part 
.IR right .
.
.TP
.BI "\-r \-\-renderer " command
Command for calling an external PDF renderer, which will be used for rendering slides to a compressed cache.
This should be either "poppler" (for using the internal renderer), "custom" (for using a renderer, which is defined in the config file) or a command.
The command should can a renderer, which renders a specific page of a PDF file to a png image of fixed size, such that it can be shown in a window with given width and height and writes the image to the standard output.
The command should contain the tokens "%file" for the PDF file name, "%page" for the page number, "%width" for the image width in pixels and "%height" for the height in pixels.
Note that a failing command will not necessarily be handled correctly or lead to a warning.

An example for a command using
.BR "mutool draw " "from the " MuPDF " project is"
.RB \[dq] "mutool draw"
.IR -F "png " -w "%width " -h "%height " -o "- %file %page\[dq]."
.
.TP
.BI "\-s \-\-scrollstep " integer
Touch pads quantify scroll events as numbers of pixels. This option sets the number of pixels, which are interpreted as the step between two pages. A larger number makes the scrolling slower.
.
.TP
.BI "\-t \-\-timer " time
.RI "Set timer to " "time" ". Possible formats are ""[m]m"", ""[m]m:ss"" and ""h:mm:ss""."
.
.TP
.BI "\-u \-\-urlsplit " character
Use this character (it may also be a sequence) to split links into a link path and a list of arguments. Using PDFs with such links can be convenient, but will make the links work only in this application. This does not follow the PDF standards. Possible arguments are
.BR embed " (for executables), " autoplay " (for videos and sounds) and " loop " (for videos and sounds)."
.
.TP
.BI "\-w \-\-pid2wid " program
Path to a program, which takes a process ID as an argument and returns the window ID of the corresponding window. This can be an executable shell script using
.BR wmctrl (1)
with the command
.B echo
.IR "$(( " "16#" "$("
.BR wmctrl " -lp | " sed " -n
.RI "\[dq]s/^0x\e([0-9a-f]\e+\e) \e+[0-9]\e+ \e+" $1 " .*$/\e1/p\[dq] " ") ))"
.
.TP
.BI "\-v \-\-video-cache " bool
If set to true, videos will be loaded to cache when reaching the slide before the one containing the video.
.
.
.SH DEFAULT KEY BINDINGS
.
Key bindings can be changed in the  configuration file. The default configuration is the following.
.TP
.B Mouse wheel
Scroll through presentation. If the presentation screen (the window showing the presentation) is the active window, all displayed pages will be updated. The duration of a page as defined by the PDF will be ignored. If the control screen (the window showing notes) is focused, only the pages on the control screen will be updated. You can continue the presentation with the page currently shown on the control screen by pressing
.BR return ". If you want to continue with the slide shown on the presentation screen, you can use the usual navigation keys or " escape .
.
.TP
.B c
.B update cache
Update cached slides if necessary. An update of the cache is also triggered by a change of the current slide and by updating the current slide.
.
.TP
.B e
.B start embedded current slide
Start all embedded applications on the currently shown slide.
.
.TP
.B E
.B start all embedded
Start all embedded applications on all slides.
.
.TP
.B g
.B go to page
Go to page (set focus to page number edit). This will make the control screen the active window.
.
.TP
.B m
.B play multimedia
Play or pause all multimedia content on the current slide.
.
.TP
.B o
.B toggle cursor
Toggle cursor visibility (only on the presentation screen).
.
.TP
.B p
.B pause timer
Pause or continue timer.
.
.TP
.B q
.B Quit
.
.TP
.B r
.B Reset timer
.
.TP
.B s
.B show overview
Show overview of all slides on the control screen.
.
.TP
.B t
.B show TOC
Show table of contents on the control screen.
.
.TP
.B u
.B reload
Check if the PDF files have changed and reload them if necessary (experimental feature).
.
.TP
.B space
.B update
Update layout, reload page and start or continue timer.
.
.TP
.BR Left ", " PageUp
.B previous
Go to previous slide and start or continue timer.
.
.TP
.BR Right ", " PageDown
.B next
Go to next slide and start or continue timer.
.
.TP
.B Up
.B previous skipping overlays
Go to the previous slide until the page label changes. In beamer presentations: Go to the last overlay of the previous slide.
.
.TP
.B Down
.B next skipping overlays
Go to the next slide until the page label changes. In beamer presentations: Go to the first overlay of the next slide.
.
.TP
.BR F11 ", " f
.B full screen
Toggle full screen of the active window.
.
.TP
.B return
.B sync from control screen
Set page number of the presentation to the page number on the control screen and start or continue timer.
.
.TP
.B escape
.B sync from presentation screen
Set page number of the control screen to the page number of the presentation. When browsing your notes, this will bring you back to the current slide. Also hide the table of contents and the overview of all slides if one of them is shown.
.
.SH FEATURES
.
.SS Links
When clicking on a link on the presentation screen, on the notes slide or on the preview of the current or next slide with the right mouse button,
.B BeamerPresenter
will try to follow the link. Links to multimedia content and embedded applications are disabled for the preview slides.
.
.SS Browse Notes
By changing the current page number in the corresponding text field, the note page and the preview of the current and next slide on the control screen will be updated immediately. The same is true if you scroll with the mouse wheel on the control screen. The presentation screen will be updated only when pressing
.BR return ", " PageUp ", or " PageDown .
You can escape this mode and go back to the current slide on the presentation by pressing
.BR escape .
.
.SS Browse Table of Contents and overview
.RB "You can show a table of contents on the control screen with shortcut " t " for quick navigation. The maximum level of subsections shown in the table of contents can be controlled with the option " \-l " or " \-\-toc-depth ". For entries with more levels, one additional level is shown as a popup menu."
.PP
.RB "An overview of all presentation slides is shown on the control screen with the key binding " s ". The number of columns in this overview mode can be controlled with the option " \-o " or " \-\-columns .
.
.SS Overlays
Multimedia content and embedded applications are aware of overlays. If a video is shown on consecutive slides with the same page label, it will continue playing without interuption when switching within these slides. The same works for embedded applications independent of the page label.
.PP
You can jump to the next or previous slide with a different page label by using the arrow keys
.BR Up " and " Down .
For presentations created with LaTeX beamer using overlays, this jumps to the next or previous slide, which differs by more than an overlay.
.
.SS Cache
Slides are rendered to a compressed cache in order to allow for much faster slide changes. The number of cached slides and the memory usage can be limited by the options
.BR cache " and " memory .
By default up to 100 MiB are used for cached slides, which is usually enough even for long presentations.
Restricting the cache size to a small (but nonzero) value can affect the performance and might lead to unstable behavior.
Caching slides can be switched off completely with the command line option
.BR -c 0.
.PP
Rendering to cache can be done using a custom PDF renderer. While
.B BeamerPresenter
is based on the Qt5 bindings of poppler, rendering to cache can be done using any renderer, which can be called from the command line, accepts a filename, page number and page size as arguments and writes a rendered PDF page as png image to standard output.
An example of such a PDF renderer, which improves both speed and quality of the output image, is
.BR "mutool draw " "from the " MuPDF " project."
.
.SS Multimedia Support
.B BeamerPresenter
can show videos, which are linked in the PDF as annotation. For each video in the presentation a slider is created and shown in the lower right corner of the control screen. Videos can also be shown in the notes, but there is no synchronization between different videos. All multimedia content can be started immediately when entering a frame by using the option
.BR \-a " or " \-\-autoplay .
.PP
Audio files which are links from the PDF to external files can also be played. Embedded sounds are not supported.
.
.SS Animations
Simple animations can be created by showing slides in rapid succession. When using LaTeX beamer, this can be achieved by using the options \\animation. The minimum delay time for the frames, which have their duration set to zero, can be specified with
.BR \-m " or " \-\-min-delay .
.
.SS Slide transitions
.BR BeamerPresenter " supports an incomplete set of slide transitions. The frame time for slide transitions can be set using " \-f " or " \-\-frame-time .
.
.SS Embedded Applications
A link in the PDF pointing to an external application will usually be handled by the desktop services. But you can also specify programs, which will be executed directly when pressing the link.
.B BeamerPresenter
will try to embed the window created by the external program in the area of the link, by which it was created.
.PP
This requires that
.B BeamerPresenter
knows the window ID of this window. The simplest way of getting the window ID is by using an external application (e.g. a shell script using wmctrl), which tells you the window ID for a given process ID. The path so such an application can be provided by the argument to
.BR \-w " or " \-\-pid2wid
or by the corresponding default value in the configuration file. If no such application is specified,
.B BeamerPresenter
will try to read the window ID from the first line of the standard output of the external program.
.
.SS Beamer option "show notes on second screen"
Beamer can combine notes and presentation into one PDF file by using the option "show slides on second screen". The resulting PDF file can be read by
.B BeamerPresenter
with the option
.BR \-p ", or " \-\-page-part
.
.
.SH CONFIG
A configuration file located at
.I $HOME/.config/beamerpresenter.conf
can be used to set key bindings, colors and default options for the command line arguments. The colors can be provided as color names known to Qt or as RGB or ARGB values in hexadecimal format.
An example configuration, which can be used as a template for setting up your own preferences, can be found at
.UR https://github.com/stiglers-eponym/BeamerPresenter
or in /etc/beamerpresenter/beamerpresenter.conf (depending on your installation).
.
.SS Key bindings
.
Key bindings are defined in the form

.BI "keys/" "modifiers + key name " = " action1" , " action2",
.BR ... .

Key names and modifiers are passed to QKeySequence, which converts them to key codes. Multiple actions can be passed to a single key code and should be separated by a comma.
The actions are case insensitive. Possible actions are
.
.TP
.B update cache
Update cached slides if necessary.
.
.TP
.BR "start embedded current slide" ", " "start embedded applications current page" ", ..."
Start all embedded applications on the currently shown slide.
.
.TP
.BR "start all embedded" " or " "start all embedded applications"
Start all embedded applications on all slides.
.
.TP
.BR "go to page" " or " "go to slide"
Go to page (set focus to page number edit). This will make the control screen the active window.
.
.TP
.B play multimedia
Play or pause all multimedia content on the current slide.
.
.TP
.B toggle cursor
Toggle cursor visibility (only on the presentation screen).
.
.TP
.B pause timer
Pause or continue timer.
.
.TP
.B quit
Quit.
.
.TP
.B reset timer
Reset timer.
.
.TP
.B show overview
Show overview of all slides on the control screen.
.
.TP
.B hide overview
Hide overview of all slides if it is shown.
.
.TP
.B show TOC
Show table of contents on the control screen.
.
.TP
.B hide TOC
Hide the table of contents if it is shown.
.
.TP
.B reload
Check if the PDF files have changed and reload them if necessary (experimental feature).
.
.TP
.B update
Update layout, reload page and start or continue timer.
.
.TP
.B previous
Go to previous slide and start or continue timer.
.
.TP
.B next
Go to next slide and start or continue timer.
.
.TP
.B previous current screen
Show the previous slide only on the currently active screen.
.
.TP
.B next current screen
Show the next slide only on the currently active screen.
.
.TP
.B previous skipping overlays
Go to the previous slide until the page label changes. In beamer presentations: Go to the last overlay of the previous slide.
.
.TP
.B next skipping overlays
Go to the next slide until the page label changes. In beamer presentations: Go to the first overlay of the next slide.
.
.TP
.B full screen
Toggle full screen of the active window.
.
.TP
.B sync from control screen
Set page number of the presentation to the page number on the control screen and start or continue timer.
.
.TP
.B sync from presentation screen
Set page number of the control screen to the page number of the presentation. When browsing your notes, this will bring you back to the current slide.
.
.SS Colors
.
.RI "Colors can be specified as name known to Qt5, an RGB value or an ARGB value in hexadecimal format, e.g. as " red ", " #ff0000 " or " #ffff0000 .
In the configuration you can define the following colors.
.TP
.BR "presentation color" "=black"
background color of the presentation window
.
.TP
.BR "notes background color" "=gray"
background color of the control screen
.
.TP
.BR "notes text color" "=black"
text color of the control screen
.
.TP
.BI "timer/" time = color
.
The timer can change its color depending on the time relative to your target presentation time. In this form you can specify colors for specific times relative to the timeout. The color of the timer will be changed linearly between two such time points.
.RI "Here " time " is the time interval (timeout - now) in seconds, e.g. " time=-60 " is one minute before you reach the timeout.
.
.SS Default values for command line arguments
.
The following default values for command line arguments can be set in the config file.
.TP
.BR autoplay =false
overwrite default value for the command line argument
.BR \-a " or " \-\-autoplay .
.
.TP
.BR autoplay-emb =false
overwrite default value for the command line argument
.BR \-A " or " \-\-autoplay-emb .
.
.TP
.BR min-delay =40
overwrite default value for the command line argument
.BR \-m " or " \-\-min-delay .
.
.TP
.BR page-part =none
set default value for the command line argument
.BR \-p " or " \-\-page-part .
.
.TP
.B timer
set default value for the command line argument
.BR \-t " or " \-\-timer .
.
.TP
.B embed
set default value for the command line argument
.BR \-e " or " \-\-embed .
.
.TP
.B blinds =8
set default value for the command line argument
.BR \-b " or " \-\-blinds
.
.TP
.B frame-time =25
set default value for the command line argument
.BR \-f " or " \-\-frame-time .
.
.TP
.B pid2wid
set default value for the command line argument
.BR \-w " or " \-\-pid2wid .
.
.TP
.B urlsplit
set default value for the command line argument
.BR \-u " or " \-\-urlsplit .
.
.TP
.BR scrollstep =200
overwrite default value for the command line argument
.BR \-s " or " \-\-scrollstep .
.
.TP
.BR cache =-1
overwrite default value for the command line argument
.BR \-c " or " \-\-cache .
.
.TP
.BR memory =100
overwrite default value for the command line argument
.BR \-M " or " \-\-memory .
.
.TP
.BR video-cache =true
overwrite default value for the command line argument
.BR \-v " or " \-\-video-cache .
.
.TP
.BR toc-depth =2
overwrite default value for the command line argument
.BR \-l " or " \-\-toc-depth .
.
.TP
.BR columns =5
overwrite default value for the command line argument
.BR \-o " or " \-\-columns .
.
.TP
.BR renderer
Set the command for an external renderer. This will set the default value of the command line argument
.BR \-r " or " \-\-renderer " to \[dq]custom\[dq].
If this option is set, the internal renderer can be used with the command line argument
.RB \[dq] \-r " poppler\[dq]."
.
.SS Local configuration file
.
Additionally to the global configuration you can specify a local configuration file, which contains settings in JSON format. The local configuration overrides the global configuration and can be overridden by command line arguments. Since this file is in JSON format, the syntax of groups of arguments has to be adapted.
.RI "E.g. instead of \[dq]" "timer/time = color1" " ...\[dq] you should write " "\[dq]timer\[dq]: {\[dq]time1\[dq]: \[dq]color1\[dq], \[dq]time2\[dq]: \[dq]color2\[dq]}," .
.RB "The local configuration file may additionally contain a map " "page times" ", which defines times at which you want to finish certain slides. It has the format " "slide number: time" " where " time " is in the format mm:ss."
.
.SH BUGS
.
Bugs can be reported at the
.UR https://github.com/stiglers-eponym/BeamerPresenter/issues
issue tracker
.UE .
.
.
.
.SH SEE ALSO
.
There are other programs, which show notes along a pdf. Some examples are
.BR pympress (1),
.BR dspdfviewer "(1) and"
.BR pdfpc (1)
